config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get '/tasks', to: 'tasks#index'
  # get '/tasks/new', to: 'tasks#new'
  # get '/tasks/:id', to: 'tasks#show', as: :task
  # post '/tasks', to: 'tasks#create'
  # get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch '/tasks/:id', to: 'tasks#update'
  # delete '/tasks/:id', to: 'tasks#destroy'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :tasks, only: [:edit, :update, :show, :destroy]
    def index
        @tasks = Task.all
    end

    def show
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        @task.save

        redirect_to task_path(@task)
    end

    def edit
    end

    def update
        @task.update(task_params)
        redirect_to task_path(@task)
    end

    def destroy
        @task.destroy
        redirect_to tasks_path
    end

    private

    def tasks
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container mt-4">
<h1>Edit task</h1>
<%= form_with model: @task do |f| %>
    <div class="mb-2">
        <%= f.label :title, "Title:", class: 'form-label fw-bold' %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-2">
        <%= f.label :details, "Details:", class: 'form-label fw-bold' %>
        <%= f.text_area :details, class: 'form-control' %>
    </div>
    <div class="form-check mt-2">
        <%= f.check_box :completed, class: 'form-check-input' %>
        <%= f.label :completed, "Completed:", class: 'form-check-label' %>
    </div>
    <%= f.submit "Update Task", class: 'btn btn-primary mt-2 fw-bold' %>
<% end %>
<hr />
<%= link_to tasks_path do %>
  <i class="fa-solid fa-clock-rotate-left"></i><span>&#8201;Back to list</span>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="container mt-4">
    <h1 class="mb-4">My Tasks</h1>
   <ul class="d-flex flex-column gap-1">
     <% @tasks.each do |task|  %>
    <% checked = task.completed %>
    <li>
        <% if task.completed %>
            <i class="fa-regular fa-square-check"></i>
        <% else %>
            <i class='fa-regular fa-square'></i>
        <% end %>
        <span>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        &#8201;&#8201;
        <i class="fa-solid fa-trash-can"></i>
        <% end %>
        </span>
    </li>
    <% end %>
    </ul>
    <hr />
    <%= link_to new_task_path do %>
    <i class="fa-solid fa-plus"></i>
    <span>&#8201;Add a new task</span>
    <% end %>

</div>

app/views/tasks/new.html.erb
<div class="container mt-4">
<h1>New task</h1>
<%= form_with model: @task do |f| %>
  <div class="mb-2">
    <%= f.label :title, "Title:", class: 'form-label fw-bold' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-2">
    <%= f.label :details, "Details:", class: 'form-label fw-bold' %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>
  <%= f.submit "Create Task", class: 'btn btn-primary mt-2 fw-bold' %>
<% end %>
<hr />

<%= link_to tasks_path do %>
  <i class="fa-solid fa-clock-rotate-left"></i><span>&#8201;Back to list</span>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container mt-4">
<div class="d-flex justify-content-between mb-4">
    <h1><%= @task.title %></h1>
    <button class="btn btn-sm border border-3">
        <i class="fa-solid fa-pen"></i>
        <%= link_to "Edit this task", edit_task_path(@task) %></button>
</div>
<div class="alert alert-dark" role="alert">
  <%= @task.details %>
</div>
<p>
    <% if @task.completed %>
            <i class="fa-regular fa-square-check"></i> <span>This task is completed</span>
        <% else %>
            <i class='fa-regular fa-square'></i> <span>This task is not completed yet</span>
    <% end %>
</p>
<hr>
<p class="text-primary"><i class='fa-solid fa-clock-rotate-left'></i> <%= link_to "Back to list", tasks_path %></p>
</div>